apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec: 
  containers:
  - name: my-container
    image: nginx
    resources:
     requests:
       memory: "512Mi"
       cpu: "1100m"
     limits:
       memory: "624Mi"
       cpu: "1600m"
