apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx2
spec:
  replicas: 10
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 2
  selector:
    matchLabels:
      app: nginx2
  template:
    metadata:
      labels: 
        app: nginx2
    spec:  
      containers:
      - name: contendor2
        image: nginx:1.14.1
        ports:
        - containerPort: 80
      
