apiVersion: v1
kind: Pod
metadata:
  name: ejemplo-pod
  labels:
    app: mi-aplicacion
spec:
  shareProcessNamespace: true 
  containers:
  - name: main-container
    image: alpine
    command: ["sh","-c", "sleep 1000"]
    volumeMounts:
    - mountPath: /data
      name: my-volume
  volumes:
  - name: my-volume
    emptyDir: {}
